# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
cache: packages
before_install:
  - sudo apt-get install -y libxml2-dev libgit2-dev
  - Rscript -e 'devtools::install_github("srvanderplas/ShoeData")'
addons:
  apt:
    update: true
env:
  global:
  - R_CHECK_FORCE_SUGGESTS=FALSE
  - _R_CHECK_FORCE_SUGGESTS_=FALSE
r_github_packages:
  - MangoTheCat/visualTest
  - srvanderplas/ShoeData
script:
  - R CMD build --no-build-vignettes .
  - R CMD check --no--vignettes ImageAlignR*tar.gz
after_success:
  - Rscript -e 'covr::codecov()'
