# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
cache: packages
before_install:
  - sudo apt-get install -y libxml2-dev libgit2-dev
addons:
  apt:
    update: true
install:
  - ./travis-tool.sh install_github MangoTheCat/visualTest
after_success:
  - Rscript -e 'covr::codecov()'
